{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    {{- include "argocd-metrics-server.labels" . | nindent 4 }}
  name: {{ include "argocd-metrics-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "argocd-metrics-server.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- if or (.Values.networkPolicy.dns.enabled) (.Values.networkPolicy.prometheus.enabled) }}
    - Egress
    {{- end }}
    {{- if .Values.networkPolicy.argocd.enabled }}
    - Ingress
    {{- end }}
  {{- if or (.Values.networkPolicy.dns.enabled) (.Values.networkPolicy.prometheus.enabled) }}
  egress:
    {{- if .Values.networkPolicy.dns.enabled }}
    - to:
        {{- if .Values.networkPolicy.dns.namespaceSelector }}
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.dns.namespaceSelector | nindent 14 }}
        {{- end }}
        {{- if .Values.networkPolicy.dns.podSelector }}
        {{- if not .Values.networkPolicy.dns.namespaceSelector }}
        - podSelector:
        {{- else }}
          podSelector:
        {{- end }}
            matchLabels:
              {{- toYaml .Values.networkPolicy.dns.podSelector | nindent 14 }}
        {{- end }}
      ports:
        - protocol: UDP
          port: 53
    {{- end }}
    {{- if .Values.networkPolicy.prometheus.enabled }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.prometheus.namespace | quote }}
          {{- if .Values.networkPolicy.prometheus.podSelector }}
          podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.prometheus.podSelector | nindent 14 }}
          {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.prometheus.port | int }}
    {{- end }}
  {{- end }}
  {{- if .Values.networkPolicy.argocd.enabled }}
  ingress:
    - from:
  {{- end }}
{{- end }}
