---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "argocd-metrics-server.labels" . | nindent 4 }}
  name: {{ include "argocd-metrics-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
  selector:
    {{- include "argocd-metrics-server.selectorLabels" . | nindent 4 }}
