{{- if and (.Values.headwind.sharedSecret.secretValue) (not .Values.headwind.sharedSecret.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "headwind-mdm.sharedSecret.secretName" . }}
data:
  shared-secret: {{ .Values.headwind.sharedSecret.secretValue | b64enc }}
{{- end }}
