---
apiVersion: v2
name: kube-ops-view
description: A Helm chart for bootstrapping kube-ops-view.
type: application
version: 3.6.1
appVersion: "23.5.0"
home: https://github.com/christianhuth/helm-charts
icon: https://codeberg.org/repo-avatars/677-c51f6426305941cab515fdd98368f0bb
maintainers:
  - name: christianhuth
    email: christian@knell.it
sources:
  - https://codeberg.org/hjacobs/kube-ops-view
dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.19.4
    condition: redis.enabled
annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: |
    - kind: added
      description: signing key to Chart.yaml
  artifacthub.io/screenshots: |
    - title: Dashboard overview of a Kubernetes cluster
      url: https://codeberg.org/hjacobs/kube-ops-view/media/branch/main/screenshot.png
    - title: Dashboard showing broken Pods
      url: https://user-images.githubusercontent.com/1127164/53682720-a2a83780-3cf8-11e9-9384-2c1df186aad4.png
  artifacthub.io/signKey: |
    fingerprint: EE24F8BB6D099E78FD704F83B5ECDBCDDD485D0E
    url: https://charts.christianhuth.de/public.key
