{{- if and (not .Values.postgresql.enabled) (not .Values.externalPostgresql.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "headwind-mdm.postgresql.secretName" . }}
data:
  {{- include "headwind-mdm.postgresql.userPasswordKey" . | nindent 2 }}: {{ .Values.externalPostgresql.auth.password | b64enc }}
{{- end }}
