{{- if (and (.Values.maildev.config.smtp.incoming.tls.enabled) (not .Values.maildev.config.smtp.incoming.tls.existingSecret)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "maildev.smtp.incoming.tls.secretName" . }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.maildev.config.smtp.incoming.tls.cert | b64enc }}
  tls.key: {{ .Values.maildev.config.smtp.incoming.tls.key | b64enc }}
{{- end }}
