name: 'Close stale issues and PRs'

on:
  schedule:
    - cron: '* 2 * * *'

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          # see https://github.com/actions/stale#all-options
          close-issue-label: "'This issue has been automatically closed because it has not had recent activity."
          close-issue-message: false
          close-pr-label: "'This PR has been automatically closed because it has not had recent activity."
          close-pr-message: false
          days-before-stale: 180
          days-before-close: 180
          exempt-issue-labels: pinned, security
          exempt-pr-labels: pinned, security
          stale-issue-label: stale
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
          stale-pr-label: stale
          stale-pr-message: 'This PR has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
