{{- if and (not .Values.umami.appSecret.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "umami.appSecret.secretName" . }}
data:
  {{- if .Values.umami.appSecret.secret }}
  app-secret: {{ .Values.umami.appSecret.secret | b64enc }}
  {{- else }}
  app-secret: {{ randAlphaNum 50 | b64enc }}
  {{- end }}
{{- end }}
