# -- Provide a name in place of `maildev`
nameOverride: ""

# -- String to fully override `"maildev.fullname"`
fullnameOverride: ""

image:
  # -- image registry
  registry: docker.io
  # -- image repository
  repository: maildev/maildev
  # -- image pull policy
  pullPolicy: Always
  # -- Overrides the image tag
  tag: "2.1.0"

# -- If defined, uses a Secret to pull an image from a private Docker registry or repository.
imagePullSecrets: []

# -- Annotations to be added to the pods
podAnnotations: {}

# -- pod-level security context
podSecurityContext: {}
  # fsGroup: 2000

# -- Number of replicas
replicaCount: 1

# -- The number of old ReplicaSets to retain
revisionHistoryLimit: 10

# -- Resource limits and requests for the controller pods.
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- container-level security context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

services:
  web:
    # -- Kubernetes service type for the web GUI
    type: ClusterIP
    # -- Kubernetes service port to use for the web GUI
    port: 1080
    # -- Pod port to use for the web GUI
    podPort: 1080
  smtp:
    # -- Kubernetes service type for the SMTP server
    type: ClusterIP
    # -- Kubernetes service port to use for the internal SMTP server
    port: 1025
    # -- Pod port to use for the internal SMTP server
    podPort: 1025
    # -- You can set the node port for the external SMTP server that should be used or leave it blank to get a random node port. Only active if `services.smtp.type == NodePort`
    nodePort:

ingress:
  # -- Enable ingress record generation
  enabled: false
  # -- IngressClass that will be be used to implement the Ingress
  className: ""
  # -- Additional annotations for the Ingress resource
  annotations: {}
    # cert-manager.io/cluster-issuer: cluster-issuer-name
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- An array with hosts and paths
  # @default -- see [values.yaml](./values.yaml)
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  # -- An array with the tls configuration
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

autoscaling:
  # -- Enable Horizontal POD autoscaling
  enabled: false
  # -- Minimum number of replicas
  minReplicas: 1
  # -- Maximum number of replicas
  maxReplicas: 100
  # -- Target CPU utilization percentage
  targetCPUUtilizationPercentage: 80
  # -- Target Memory utilization percentage
  targetMemoryUtilizationPercentage: 80

# -- Node labels for pod assignment
nodeSelector: {}

# -- Toleration labels for pod assignment
tolerations: []

# -- Affinity settings for pod assignment
affinity: {}

# -- additional environment variables to be added to the pods
extraEnv: []

maildev:
  config:
    https:
      # -- Switch from http to https protocol
      enabled: false
      # -- The ssl cert file
      cert: ""
      # -- The ssl private key
      key: ""
    # -- Log a JSON representation of each incoming mail
    logMailContents: false
    # -- Directory for persisting mail
    mailDirectory: "/home/node/maildev-data"
    modes:
      # -- Run maildev in silent mode to disable the startup messages
      silent: true
      # -- Run maildev in verbose mode
      verbose: false
    smtp:
      # -- Comma separated list of SMTP extensions to NOT advertise (SMTPUTF8, PIPELINING, 8BITMIME)
      hideExtensions: ""
      incoming:
        # -- Name of an existing secret containing the password for the incoming SMTP mail. If set `maildev.config.smtp.incoming.password` will be ignored. Key needs to be `smtp-incoming-password`.
        existingSecret: ""
        # -- SMTP password for incoming mail
        password: ""
        # -- SMTP user for incoming mail
        username: ""
      outgoing:
        autoRelay:
          # -- Enabling the auto relay mode will automatically send each email to it's recipient without the need to click the "Relay" button. The outgoing email options are required to enable this feature.
          enabled: false
          # -- Optionally define a single email address which Maildev will forward all emails to instead of the original recipient
          mail: ""
          # -- The additional configuration for what email addresses you would like to allow or deny.
          rules: []
            # [
            #   { "allow": "*" },
            #   { "deny": "*@test.com" },
            #   { "allow": "ok@test.com" },
            #   { "deny": "*@utah.com" },
            #   { "allow": "johnny@utah.com" }
            # ]
        # -- Name of an existing secret containing the password for the outgoing SMTP mail. If set `maildev.config.smtp.outgoing.password` will be ignored. Key needs to be `smtp-outgoing-password`.
        existingSecret: ""
        # -- SMTP host for outgoing mail
        host: ""
        # -- SMTP password for outgoing mail
        password: ""
        # -- SMTP port for outgoing mail
        port: 25
        # -- Use SMTP SSL for outgoing mail
        ssl: false
        # -- SMTP user for outgoing mail
        username: ""
    web:
      # -- Disable the use of the web interface. Useful for unit testing
      disabled: false
      # -- Name of an existing secret containing the password for the GUI. If set `maildev.config.web.password` will be ignored. Key needs to be `web-password`.
      existingSecret: ""
      # -- Password for the GUI
      password: ""
      # -- Username for the GUI
      username: ""
  persistence:
    # -- Use a PVC to persist data
    enabled: false
    # -- The desired access modes the volume should have.
    accessModes:
      - ReadWriteOnce
    # -- Annotations to be added to the PersistentVolumeClaim
    annotations: {}
    # To clean some old mails when persistence is enabled
    cron:
      # -- Enable the creation of a cronjob to periodically delete old emails
      enabled: false
      config:
        # -- How old emails may be before they get deleted
        daysToKeep: 15
        # -- The schedule on which the cronjob should run
        schedule: "0 1 * * *"
      image:
        # -- Image registry
        registry: docker.io
        # -- Image repository
        repository: busybox
        # -- Image pull policy
        pullPolicy: Always
        # -- Overrides the image tag
        tag: latest
    # -- Provide an existing PersistentVolumeClaim
    existingClaim: ""
    # -- Name of the StorageClass required by the claim.
    storageClassName: ""
    # -- Represents the minimum and maximum resources the volume should have.
    resources:
      requests:
        storage: 2Gi
